/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as JuridicoRouteImport } from './routes/juridico'
import { Route as OperacoesRouteImport } from './routes/operacoes'
import { Route as ModulosModuleIdSectionIdRouteImport } from './routes/modulos.$moduleId.$sectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const JuridicoRoute = JuridicoRouteImport.update({
  id: '/juridico',
  path: '/juridico',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacoesRoute = OperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosModuleIdSectionIdRoute =
  ModulosModuleIdSectionIdRouteImport.update({
    id: '/modulos/$moduleId/$sectionId',
    path: '/modulos/$moduleId/$sectionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/juridico': typeof JuridicoRoute
  '/operacoes': typeof OperacoesRoute
  '/modulos/$moduleId/$sectionId': typeof ModulosModuleIdSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/juridico': typeof JuridicoRoute
  '/operacoes': typeof OperacoesRoute
  '/modulos/$moduleId/$sectionId': typeof ModulosModuleIdSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compliance': typeof ComplianceRoute
  '/juridico': typeof JuridicoRoute
  '/operacoes': typeof OperacoesRoute
  '/modulos/$moduleId/$sectionId': typeof ModulosModuleIdSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/compliance'
    | '/juridico'
    | '/operacoes'
    | '/modulos/$moduleId/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compliance'
    | '/juridico'
    | '/operacoes'
    | '/modulos/$moduleId/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/compliance'
    | '/juridico'
    | '/operacoes'
    | '/modulos/$moduleId/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComplianceRoute: typeof ComplianceRoute
  JuridicoRoute: typeof JuridicoRoute
  OperacoesRoute: typeof OperacoesRoute
  ModulosModuleIdSectionIdRoute: typeof ModulosModuleIdSectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/juridico': {
      id: '/juridico'
      path: '/juridico'
      fullPath: '/juridico'
      preLoaderRoute: typeof JuridicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacoes': {
      id: '/operacoes'
      path: '/operacoes'
      fullPath: '/operacoes'
      preLoaderRoute: typeof OperacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/$moduleId/$sectionId': {
      id: '/modulos/$moduleId/$sectionId'
      path: '/modulos/$moduleId/$sectionId'
      fullPath: '/modulos/$moduleId/$sectionId'
      preLoaderRoute: typeof ModulosModuleIdSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComplianceRoute: ComplianceRoute,
  JuridicoRoute: JuridicoRoute,
  OperacoesRoute: OperacoesRoute,
  ModulosModuleIdSectionIdRoute: ModulosModuleIdSectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
