/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulosModuleIdSectionIdRouteImport } from './routes/modulos.$moduleId.$sectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosModuleIdSectionIdRoute =
  ModulosModuleIdSectionIdRouteImport.update({
    id: '/modulos/$moduleId/$sectionId',
    path: '/modulos/$moduleId/$sectionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/modulos/$moduleId/$sectionId': typeof ModulosModuleIdSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/modulos/$moduleId/$sectionId': typeof ModulosModuleIdSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/modulos/$moduleId/$sectionId': typeof ModulosModuleIdSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/modulos/$moduleId/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/modulos/$moduleId/$sectionId'
  id: '__root__' | '/' | '/modulos/$moduleId/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModulosModuleIdSectionIdRoute: typeof ModulosModuleIdSectionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/$moduleId/$sectionId': {
      id: '/modulos/$moduleId/$sectionId'
      path: '/modulos/$moduleId/$sectionId'
      fullPath: '/modulos/$moduleId/$sectionId'
      preLoaderRoute: typeof ModulosModuleIdSectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModulosModuleIdSectionIdRoute: ModulosModuleIdSectionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
